name: taksi
description: "PayGo"

publish_to: 'none' 


version: 5.0.0+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  url_launcher: ^6.3.1
  flutter_svg: ^1.1.6
  permission_handler: ^11.3.1
  android_intent_plus: ^5.2.0
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.3.3
  observer: ^0.0.1
  flutter_local_notifications: ^18.0.1
  icons_launcher: ^3.0.0
  lottie: ^3.1.3
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  connectivity_plus: ^6.1.0
  rxdart: ^0.28.0
  async: ^2.11.0
  geolocator: ^13.0.1
  font_awesome_flutter: ^10.8.0
  pinput: ^5.0.0
  otp_timer_button: ^1.1.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  easy_localization: ^3.0.7
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  fluid_bottom_nav_bar: ^1.4.0
  hooks_riverpod: ^2.6.1
  avatar_glow: ^3.0.1
  flutter_rating_bar: ^4.0.1
  flutter_gradient_animation_text: ^1.0.2
  bottom_picker: ^2.10.1
  animated_toggle_switch: ^0.8.4
  smart_auth: ^3.2.0
  toastification: ^2.3.0
  expansion_tile_card: ^3.0.0
  emoji_picker_flutter: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  # common:
  #   path: lib/common
    
icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:


  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/ 
    - assets/translations/   
    - .env
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
    - family: Number
      fonts:
        - asset: assets/fonts/FE-FONT.TTF
